openapi: 3.0.0
info:
  title: EMBRAPA - Dados da Vitivinicultura
  description: This is a simple API for a FIAP - Tech Challenge
  contact:
    email: diogo.r.lessa@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: /
paths:
  /producao:
    get:
      summary: searches Producao
      description: |
        By passing in the appropriate options, you can search for
        available Producao info in the system
      operationId: search_producao
      parameters:
      - name: produto
        in: query
        description: search for a product name
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: ano
        in: query
        description: search for a specific year
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProducaoItem'
                x-content-type: application/json
        "400":
          description: bad input parameter
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /processamento:
    get:
      summary: searches Processamento
      description: |
        By passing in the appropriate options, you can search for
        available Processamento info in the system
      operationId: search_processamento
      parameters:
      - name: categoria
        in: query
        description: "search within a category (Viniferas, Americanas e Hibridas,\
          \ Uvas de mesa, or Sem classificacao)"
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: cultivar
        in: query
        description: search for a cultivar name
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: ano
        in: query
        description: search for a specific year
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProcessamentoItem'
                x-content-type: application/json
        "400":
          description: bad input parameter
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /comercializacao:
    get:
      summary: searches Comercializacao
      description: |
        By passing in the appropriate options, you can search for
        available Comercializacao info in the system
      operationId: search_comercializacao
      parameters:
      - name: produto
        in: query
        description: search for a product name
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: ano
        in: query
        description: search for a specific year
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ComercializacaoItem'
                x-content-type: application/json
        "400":
          description: bad input parameter
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /importacao:
    get:
      summary: searches Importacao
      description: |
        By passing in the appropriate options, you can search for
        available Importacao info in the system
      operationId: search_importacao
      parameters:
      - name: categoria
        in: query
        description: "search within a category (Vinhos de mesa, Espumantes, Uvas frescas,\
          \ or Suco de uva)"
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: pais
        in: query
        description: search for a country name
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: ano
        in: query
        description: search for a specific year
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ImportacaoItem'
                x-content-type: application/json
        "400":
          description: bad input parameter
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /exportacao:
    get:
      summary: searches Exportacao
      description: |
        By passing in the appropriate options, you can search for
        available Exportacao info in the system
      operationId: search_exportacao
      parameters:
      - name: categoria
        in: query
        description: "search within a category (Vinhos de mesa, Espumantes, Uvas frescas,\
          \ or Suco de uva)"
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: pais
        in: query
        description: search for a country name
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: ano
        in: query
        description: search for a specific year
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ExportacaoItem'
                x-content-type: application/json
        "400":
          description: bad input parameter
      x-openapi-router-controller: swagger_server.controllers.default_controller
components:
  schemas:
    ProducaoItem:
      required:
      - ano
      - produto
      - quantidade
      type: object
      properties:
        produto:
          type: string
          example: VINHO DE MESA
        ano:
          type: integer
          format: int32
          example: 1970
        quantidade:
          type: integer
          format: int32
          example: 217208604
      example:
        ano: 1970
        produto: VINHO DE MESA
        quantidade: 217208604
    ProcessamentoItem:
      required:
      - ano
      - categoria
      - cultivar
      - quantidade
      type: object
      properties:
        categoria:
          type: string
          example: Viniferas
        cultivar:
          type: string
          example: Carmenere
        ano:
          type: integer
          format: int32
          example: 1970
        quantidade:
          type: integer
          format: int32
          example: 1235
      example:
        ano: 1970
        cultivar: Carmenere
        categoria: Viniferas
        quantidade: 1235
    ComercializacaoItem:
      required:
      - ano
      - categoria
      - cultivar
      - quantidade
      type: object
      properties:
        categoria:
          type: string
          example: VINHO DE MESA
        cultivar:
          type: string
          example: Tinto
        ano:
          type: integer
          format: int32
          example: 1970
        quantidade:
          type: integer
          format: int32
          example: 83300735
      example:
        ano: 1970
        cultivar: Tinto
        categoria: VINHO DE MESA
        quantidade: 83300735
    ImportacaoItem:
      required:
      - ano
      - pais
      - quantidade
      - valor
      type: object
      properties:
        pais:
          type: string
          example: Chile
        ano:
          type: integer
          format: int32
          example: 1970
        quantidade:
          type: integer
          format: int32
          example: 162370
        valor:
          type: integer
          format: int32
          example: 101819
      example:
        ano: 1970
        valor: 101819
        quantidade: 162370
        pais: Chile
    ExportacaoItem:
      required:
      - ano
      - pais
      - quantidade
      - valor
      type: object
      properties:
        pais:
          type: string
          example: Estados Unidos
        ano:
          type: integer
          format: int32
          example: 1970
        quantidade:
          type: integer
          format: int32
          example: 11200
        valor:
          type: integer
          format: int32
          example: 11200
      example:
        ano: 1970
        valor: 11200
        quantidade: 11200
        pais: Estados Unidos

